### ISSUE TITLE
Does not start in pub serve mode

### ISSUE THREAD

**Issue by dentra** [dart-lang/angular2_components#4] opened 2016-10-27 15:08 UTC
Can't start using because of exception trown in `pub serve` mode:

```
ORIGINAL EXCEPTION: No top-level method '_url' declared.

NoSuchMethodError: method not found: '_url'
Receiver: top-level
Arguments: [...](anonymous function) @ VM9598:1

ORIGINAL STACKTRACE:(anonymous function) @ VM9598:1
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:184)
#1      _url (package:angular2_components/src/framework_stabilizers/testability.dart:18:25)
#2      testabilitiesEnabled (package:angular2_components/src/framework_stabilizers/testability.dart:21:35)
#3      testabilitiesEnabled (package:angular2_components/src/framework_stabilizers/testability.dart:21:12)
...
```

in release mode after 'pub build' seems started properly.

**Comment by thebitguru** [comment] 2016-11-01 08:02
Are you using any component?  If so, which one?  I am new to dart and angular 2, but I was able to get a material-button to show up and function using `pub serve` without any issues.

**Comment by dentra** [comment] 2016-11-02 07:44
@thebitguru, yes of course. I've created simple page with oly one material-button with no luck too.

those code thrown a error:
```dart
// We are getting the URL from JS land because Dart's URI.base is more expensive
@JS('window.location.href')
external String get _url; // <-- THIS IS NULL

/// Check if the enableTestabilities URL parameter is set to true.
final bool testabilitiesEnabled = _url.contains('enableTestabilities');
```

**Comment by dentra** [comment] 2016-11-02 07:51
it is crashes only in dartium in chrome it is works

**Comment by zoechi** [comment] 2016-11-02 07:52
But that code doesn't seem to be related to Angular2 or angular2_components

**Comment by dentra** [comment] 2016-11-02 08:02
@zoechi this code from angular2_components https://github.com/dart-lang/angular2_components/blob/master/lib/src/framework_stabilizers/testability.dart

**Comment by zoechi** [comment] 2016-11-02 08:22
I see, sorry for the noise.

**Comment by thebitguru** [comment] 2016-11-02 14:38
@dentra, I can confirm that a simple instance of material-button is working for me in both Chrome and Dartium.  Can you share your template code?

**Comment by nshahan** [comment] 2016-11-22 22:09
@dentra Have you found a solution to this issue? Can we close this?

**Comment by TedSander** [comment] 2016-11-25 07:35
What version of Dartium are you using? I'm pretty sure this is from a version of Dartium which doesn't have the JS interop support this code is relying on.

**Comment by matanlurey** [comment] 2016-12-24 02:23
I am closing this due to ~99% being Dartium version, please re-open if you have more issues.

**Closed by matanlurey** 2016-12-24 02:23 UTC
